FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json ./frontend/
RUN cd frontend && npm ci

COPY frontend/ ./frontend/

WORKDIR /app/frontend

RUN npm run build

CMD ["npm", "start"]

EXPOSE 3000