services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    depends_on:
      - backend
    networks:
      - infra-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.github-profile.rule=Host(`github-profile.prismabitetesting.xyz`)"
      - "traefik.http.services.github-profile.loadbalancer.server.port=3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      - PORT=3001
    networks:
      - infra-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.github-profile-api.rule=Host(`github-profile.prismabitetesting.xyz`) && PathPrefix(`/api`)"
      - "traefik.http.services.github-profile-api.loadbalancer.server.port=3001"

networks:
  infra-public:
    external: true